# -*- coding: utf-8 -*-
"""ProyectoFotos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tMRtYn_fRZdqp27jxUdJpqvk7OcMjaTz
"""

# ============================================
# SUBIR Y DESCOMPRIMIR DATASET
# ============================================

from google.colab import files
import os

print("Sube tu archivo .zip del dataset descargado de Roboflow (YOLOv8 format)")
uploaded = files.upload()

# obtener nombre del archivo
dataset_zip = list(uploaded.keys())[0]

# crear carpeta y descomprimir
!mkdir dataset
!unzip -q "$dataset_zip" -d dataset

print("Dataset descomprimido en /content/dataset")

# ============================================
# VERIFICAR ESTRUCTURA
# ============================================

for root, dirs, files in os.walk("/content/dataset", topdown=True):
    level = root.replace("/content/dataset", "").count(os.sep)
    indent = " " * 2 * level
    print(f"{indent}{os.path.basename(root)}/")
    subindent = " " * 2 * (level + 1)
    for f in files[:3]:
        print(f"{subindent}{f}")

# ============================================
# INSTALAR YOLOv8 (Ultralytics)
# ============================================

!pip install ultralytics --quiet

from ultralytics import YOLO
import torch

print(" YOLOv8 instalado correctamente")
print("Versión de PyTorch:", torch.__version__)

# ============================================
# ENTRENAMIENTO DEL MODELO
# ============================================

# Cambia la ruta si tu data.yaml está en una subcarpeta
data_path = "/content/dataset/data.yaml"

# Cargar modelo base (pequeño y rápido)
model = YOLO("yolov8n.pt")

# Entrenar
model.train(
    data=data_path,     # ruta del YAML
    epochs=50,         # puedes cambiarlo a 50 si tienes poco tiempo
    imgsz=640,          # tamaño de imagen (recomendado)
    batch=8,            # si da error de memoria, baja a 4
    project="alpr_train",  # carpeta donde se guardan los resultados
    name="exp1"
)

# ============================================
# RESULTADOS DEL ENTRENAMIENTO
# ============================================

print("\n Entrenamiento finalizado. Resultados guardados en /content/alpr_train/exp1/")
print("Pesos entrenados: /content/alpr_train/exp1/weights/best.pt")

# ============================================
# PRUEBA DEL MODELO (IMÁGENES DE VALIDACIÓN)
# ============================================

# Cargar el modelo entrenado
model = YOLO("/content/alpr_train/exp1/weights/best.pt")

# Predecir sobre imágenes de validación
!mkdir -p results
model.predict(source="/content/dataset/valid/images", save=True, imgsz=640, conf=0.5)

print("Resultados guardados en /content/runs/detect/predict/")

# ============================================
# FIN DEL PIPELINE
# ============================================

print("""
PIPELINE COMPLETO:
1. Dataset cargado manualmente (sin API)
2. YOLOv8 entrenado con tus datos
3. Resultados guardados y listos para análisis
""")

#from google.colab import files
#files.download("/content/alpr_train/exp1/weights/best.pt")

from google.colab import files
uploaded = files.upload()  # selecciona tu imagen de prueba

from ultralytics import YOLO
import os
from IPython.display import Image

# Cargar tu modelo entrenado
model = YOLO("/content/alpr_train/exp1/weights/best.pt")

# Reemplaza 'nombre_imagen.jpg' con el nombre de tu archivo
results = model.predict(source="placa28.jpeg", save=True, conf=0.5)

# Get the directory where the results were saved
results_dir = results[0].save_dir
# Get the full path to the saved image
saved_image_path = results[0].path

# Display the image with detections
Image(filename=saved_image_path, width=600)

"""#Reconocimiento de texto"""

# Dependencias (ejecutar antes si aún no las instalaste) ----------
!sudo apt install -y tesseract-ocr libtesseract-dev libleptonica-dev
!pip install pytesseract easyocr opencv-python-headless ultralytics

import cv2
import numpy as np
import pytesseract
import re
from ultralytics import YOLO
import easyocr

# Carga modelos
yolo = YOLO("/content/alpr_train/exp1/weights/best.pt")  # tu modelo
easy_reader = easyocr.Reader(['es'], gpu=False)  # fallback, cambia gpu=True si tienes GPU y easyocr la soporta

# Configuración de Tesseract: OEM 3 (LSTM), PSM 7 (una sola línea), y whitelist de caracteres válidos.
TESS_CONFIG = r'--oem 3 --psm 7 -c tessedit_char_whitelist=ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-'

# Regex patrón de placas mexicanas: 3 letras - 3 dígitos - 1 letra
PLATE_REGEX = re.compile(r'([A-Z]{3})[-\s]?(\d{3})[-\s]?([A-Z])')

# Mapeos de sustituciones comunes (errores típicos)
SUBSTITUTIONS = {
    '°': '-',  # Símbolo grado -> guion
    'º': '-',
    ' ': '',
    '—': '-',
    '–': '-',
    '_': '-',
    '|': 'I',
    '¡': 'I',
    '¿': '?',
    '$': 'S',  # Manualmente se revisa
    ']': '',
    '[': '',
    '¡': 'I'
}

# Heurística para corregir confusiones entre O/0, I/1, Z/2, S/5, B/8
CHAR_CONFUSIONS = {
    '0':'O', 'O':'O',
    '1':'1', 'I':'1', 'L':'1',
    '2':'2', 'Z':'2',
    '5':'5', 'S':'5',
    '8':'8', 'B':'8'
}

def postprocess_text(raw_text):
    """Limpia y normaliza texto OCR bruto."""
    if raw_text is None:
        return ''
    s = raw_text.strip()
    # llevar a mayusculas
    s = s.upper()
    # aplicar sustituciones simples
    for k,v in SUBSTITUTIONS.items():
        s = s.replace(k, v)
    # eliminar caracteres no permitidos (dejamos A-Z, 0-9 y '-')
    s = re.sub(r'[^A-Z0-9-]', '', s)
    return s

def try_fix_by_pattern(txt):
    """Intenta extraer patrón AAA-999-A desde cualquier variante en txt."""
    m = PLATE_REGEX.search(txt)
    if not m:
        return None
    # normalizar con guiones
    groups = m.groups()
    fixed = f"{groups[0]}-{groups[1]}-{groups[2]}"
    return fixed

def ocr_with_tesseract(img):
    """Ejecuta Tesseract sobre imagen (grayscale or binarized)."""
    try:
        txt = pytesseract.image_to_string(img, config=TESS_CONFIG)
    except Exception as e:
        print("Tesseract error:", e)
        txt = ""
    return postprocess_text(txt)

def ocr_with_easyocr(img):
    """Fallback con EasyOCR. Devuelve el texto concatenado."""
    try:
        results = easy_reader.readtext(img)
        # easyocr devuelve lista de (bbox, text, conf)
        if not results:
            return ""
        # ordenar por bbox x para formar secuencia
        results_sorted = sorted(results, key=lambda x: x[0][0][0])
        txt = "".join([r[1] for r in results_sorted])
        return postprocess_text(txt)
    except Exception as e:
        print("EasyOCR error:", e)
        return ""

def preprocess_for_ocr(crop):
    """Preprocesamiento intensivo: escala, CLAHE, blur, sharpen, binarize, morph ops."""
    # Escalar para que la altura sea alrededor de 120-200 px (más detalles)
    h, w = crop.shape[:2]
    target_h = 160
    scale = target_h / float(h) if h>0 else 1.0
    new_w = max(200, int(w * scale))
    crop = cv2.resize(crop, (new_w, target_h), interpolation=cv2.INTER_LINEAR)

    gray = cv2.cvtColor(crop, cv2.COLOR_BGR2GRAY)
    # CLAHE para mejorar contraste
    clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8,8))
    gray = clahe.apply(gray)
    # Denoise preserving edges
    gray = cv2.bilateralFilter(gray, d=9, sigmaColor=75, sigmaSpace=75)
    # Unsharp mask (sharpen)
    gaussian = cv2.GaussianBlur(gray, (0,0), sigmaX=3)
    sharp = cv2.addWeighted(gray, 1.5, gaussian, -0.5, 0)
    # Morph close to fill gaps in characters
    kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (3,3))
    morph = cv2.morphologyEx(sharp, cv2.MORPH_CLOSE, kernel, iterations=1)
    # Adaptive threshold (binarización local)
    thresh = cv2.adaptiveThreshold(morph, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
                                   cv2.THRESH_BINARY, 35, 15)
    # Optional: invert if background is dark
    # if np.mean(thresh) < 127:
    #    thresh = 255 - thresh
    return thresh

def recognize_plate_from_image(image_path, save_crops=False, visualize=False):
    """Pipeline completo: detect -> recortar -> preprocess -> ocr -> postprocess -> validar."""
    img = cv2.imread(image_path)
    if img is None:
        raise FileNotFoundError(image_path)
    results = yolo(image_path, conf=0.35, iou=0.5)  # ajustar conf si detecta de más o de menos
    detections = results[0].boxes
    outputs = []
    for i, box in enumerate(detections):
        x1, y1, x2, y2 = map(int, box.xyxy[0])
        crop = img[y1:y2, x1:x2]
        pre = preprocess_for_ocr(crop)

        # intentar Tesseract
        ttxt = ocr_with_tesseract(pre)
        fixed = try_fix_by_pattern(ttxt)
        method = "tesseract"
        if fixed is None or len(fixed) < 6:
            # si no cumple patron, fallback a easyocr
            eout = ocr_with_easyocr(pre)
            fixed = try_fix_by_pattern(eout) or try_fix_by_pattern(ttxt + eout)
            method = "easyocr" if fixed and fixed==try_fix_by_pattern(eout) else "tesseract+easyocr"
        # Si todavía no encontramos patrón, intentamos heurística simple:
        if fixed is None:
            # aplicar reemplazos adicionales y reintentar
            t2 = ttxt
            for k,v in CHAR_CONFUSIONS.items():
                t2 = t2.replace(k, v)
            t2 = postprocess_text(t2)
            fixed = try_fix_by_pattern(t2)
            if fixed:
                method = "heuristic_fix"

        # fallback final: si nada, devolver la mejor cadena limpia (sin patrón)
        best_guess = fixed if fixed else (ttxt if len(ttxt)>0 else eout)
        if save_crops:
            cv2.imwrite(f"crop_{i}.jpg", crop)
            cv2.imwrite(f"crop_pre_{i}.jpg", pre)
        outputs.append({
            "bbox": (x1,y1,x2,y2),
            "raw_tesseract": ttxt,
            "raw_easyocr": eout if 'eout' in locals() else '',
            "plate": best_guess,
            "method": method
        })
        if visualize:
            print(outputs[-1])
    return outputs

res = recognize_plate_from_image("placa32.jpeg", save_crops=True, visualize=True)
print(res)

import re

def limpiar_placa(texto):
    """
    Limpia y valida el texto OCR para dejar solo formato AAA999A (7 caracteres).
    """
    if not texto:
        return ""

    # Pasar a mayúsculas
    texto = texto.upper()

    # Reemplazar caracteres comunes mal detectados
    sustituciones = {
        '°': '-', 'º': '-', '—': '-', '–': '-', '_': '-',
        #'O': '0', 'D': '0',  # a veces confunde O con cero
        #'S': '5', 'B': '8',  # letras que parecen números
        #'|': '1', 'I': '1', 'L': '1',
        '$': 'S',
        ']': '', '[': '', ' ': '', '.': '', ',': ''
    }
    for k, v in sustituciones.items():
        texto = texto.replace(k, v)

    # Eliminar todo lo que no sea letra o número
    texto = re.sub(r'[^A-Z0-9]', '', texto)

    # Buscar patrón de 3 letras seguidas de 3 números y 1 letra
    patron = re.search(r'([A-Z]{3})(\d{3})([A-Z])', texto)
    if patron:
        return "".join(patron.groups())  # AAA999A

    # Si no lo encuentra, truncar a los primeros 7 caracteres válidos
    return texto[:7]

texto = pytesseract.image_to_string(thresh, config="--psm 7")
print("Texto detectado en la placa:", texto)

texto_raw = pytesseract.image_to_string(thresh, config="--psm 7")
placa_limpia = limpiar_placa(texto_raw)
print("Texto detectado en la placa:", placa_limpia)